version: '3.3'

services:
  database:
    platform: linux/x86_64
    container_name: "db"
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'market'
      MYSQL_USER: 'raaxiim'
      MYSQL_PASSWORD: 'Raax11m17'
      MYSQL_ROOT_PASSWORD: 'abc'
    ports:
      - '3307:3306'