spring:
  liquibase:
    enabled: true
    change-log: classpath:sql/changelog-master.yml
  datasource:
    url: jdbc:mysql://localhost:3306/market
    username: raaxiim
    password: Raax11m17
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8088

storage:
  photoLocation: assets/photos
cm:
  address: localhost:8088
