spring:
  datasource:
    url: jdbc:mysql://localhost:3307/market
    username: raaxiim
    password: Raax11m17
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
    enabled: false
server:
  port: 8088

storage:
  photoLocation: assets/photos
cm:
  address: localhost:8088
